### ISSUE TITLE
react native error: object prototype may only be an object or null

### ISSUE THREAD

**Issue by uriva** [isaacs/inherits#30]
Hi,
While running this library from react-native dependencty (`util`) I'm getting an error:

`object prototype may only be an object or null` from inherits_browser.js:5:35.

Still trying to figure out why and how, but deleting the newer clause solves the problem. Have you encountered anything like this?

(version 2.0.1 with react native 0.55.4)

**Comment by Aniket-Engg** [comment]
facing same in angular...any suggested solution?

**Comment by isaacs** [comment]
That error would mean that `superCtor.prototype` is not an object.  What arguments are being passed in? Do you have the rest of the stack trace?

**Comment by Aniket-Engg** [comment]
In my case, this was being used quite internally in an NPM module, so i am not sure what is actually being passed.

**Comment by goto-bus-stop** [comment]
FWIW for reporters in this thread, if you got this error through the `util` module, you should also change your code or file bugs on your dependencies that use it this way, because it will likely break again in a future major version. `util.inherits` is supposed to throw an error if the superclass is missing, and we might put a wrapper around this package to do the same.

If you use `require('inherits')` directly, all is fine of course!
