### ISSUE TITLE
TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by aryzing** [isaacs/inherits#38]
When using in Chrome 89, getting the following error,

```
Uncaught TypeError: Object prototype may only be an Object or null: undefined
```

on this code,

https://github.com/isaacs/inherits/blob/master/inherits_browser.js#L6

**Comment by kitsune7** [comment]
I've had the same issue. It could be related to [this line](https://github.com/isaacs/inherits/blob/9a2c29400c6d491e0b7beefe0c32efa3b462545d/inherits.js#L2). There's not a dependency declared for `util` in `package.json` right? Where is it expecting to find the package?

**Comment by pavlovp** [comment]
I'm newbie to JS, but this seems to be commonjs package, commonjs is for node - the browser do not understand module.exports. Browsers understand native ES modules

**Comment by isaacs** [comment]
JavaScript has classes now.  You really shouldn't need this module for almost anything.  And yes, it is written for Node, so if you are using it in the browser and seeing errors there, it's because something is getting transpiled/browserified/etc from Node code for use in the browser, and perhaps it is not properly handling this module.

Hope this helps :)
